- CMakeLists.txt
- Needed for CPU model execution
> Add libmkl_vml_def

- CMakeLists.txt
> Add libmkl_rt.so dependency for missing symbols

- CMakeLists.txt
- src/libtorch.cc
- extern initialzied while being declared in vision.h
PS: Needed by 21.03 container since it picks up the new Torchvision changes that cause this issue.
> Disable Werror during torchvision vision header

- CMakeLists.txt
- README.md
- User must always manually pass the TRITON_PYTORCH_DOCKER_IMAGE cmake flag
- Update Readme for NGC PyTorch container based build
> Remove default TRITON_PYTORCH_DOCKER_IMAGE value

- src/libtorch.cc
`Avg request latency: 138887 usec (overhead 42 usec + queue 80 usec + compute input 13897 usec + compute infer 10288 usec + compute output 114580 usec)`
`Avg request latency: 128321 usec (overhead 36 usec + queue 75 usec + compute input 20 usec + compute infer 128107 usec + compute output 83 usec)`
> Fix timing for GPU execution

- README.md
- src/libtorch.cc
- src/libtorch_utils.cc
- src/libtorch_utils.h
- specified in parameters in model config
Use a resnet50 model to verify if it works and here are the numbers
```
libtorch.cc:200] Optimized execution is disabled
First inference time (s): 1.056
libtorch.cc:200] Optimized execution is enabled
First inference time (s): 1.137
Speedup for first inference when optimized execution is disabled: 7% 
```
PS: Throughput is identical in both cases when using perf_analyzer
> Add support for disabling optimized execution

- src/libtorch.cc
> Fix typo that causes build failure

- CMakeLists.txt
libiomp5.so -> libomp.so
This change must go into r21.06 branch.
@dzier We usually create the r21.06 branches during codefreeze right?
> WIP: Change omp library name, moving to PyTorch 21.06

- src/libtorch.cc
Error reported is of the form `output 'output__0' is a scalar which is not supported.`
> Return appropriate error if the output is a scalar

- README.md
Documenting current behavior for now. Should be updated with tritonserver enhancement to detect cuda context corruption.
> Document effects of libtorch asynchronous execution on backend

- README.md
- src/libtorch.cc
- Support for InferenceMode was added in Pytorch 1.9.0
Read more here: https://pytorch.org/cppdocs/notes/inference_mode.html
> Use InferenceMode guard instead of NoGradGuard

- README.md
- src/libtorch.cc
- src/libtorch_utils.h
This supercedes #42.
Some models seem to perform poorly with the default set of JIT optimizations. Expose some of these API parameters in the config so that these models can be run in Triton.
> Additional parameters to control PyTorch JIT and fuser options

- src/libtorch.cc
- Some models outputs can be on a device different than the model itself
Error before:
```
pinned buffer: failed to perform CUDA copy: invalid argument
```
Fixes: https://github.com/triton-inference-server/server/issues/2641
> Use tensor device instead of model device

- src/libtorch.cc
- Only works for when the model has 1 input type of kind DictType.
- For such a model the input names need not use the `name__index` convention. 
- The names of the inputs are used as the key for the input dictionary.
Sample error message:
```
+----------------------------------+---------+-----------------------------------------------------------------+
| Model                            | Version | Status                                                          |
+----------------------------------+---------+-----------------------------------------------------------------+
| libtorch_list_dict               | 1       | UNAVAILABLE: Internal: An input of type 'Dict(str, Tensor)[]' w |
|                                  |         | as detected in the model. Only a single input of type …
```
> Add support for passing inputs as a dictionary to model

- src/libtorch.cc
- Allow input tensor names without naming convention when they match input argument names for forward function
Eg for the model below:
```
class Add(nn.Module):
def __init__(self):
super(Add, self).__init__()
def forward(self, input0, input1):
return input0 + input1
```
The input names (when not following the naming convention) would be **input0** and **input1**.
- Include device kind in logging of instance creation
Old:
```
libtorch.cc:1412] TRITONBACKEND_ModelInstanceInitialize: libtorch_float32_float32_float32 (device 0)
```
New: 
```
libtorch.cc:1412] TRITONBACKEND_ModelInstanceInitialize: libtorch_float32_float32_float32 (GPU device 0)
```
> Allow input names from model metadata 

- README.md
- src/libtorch.cc
This PR allows a Triton user to enable multiple instances of a model on the same device to share weights. This is turned off by default and can be enabled via a model config parameter, "ENABLE_WEIGHT_SHARING."
Enabling weight reuse can reduce memory usage of model loading and inference. It should not be used with models that maintain state (due to the reusing of weights).
Related server test change: https://github.com/triton-inference-server/server/pull/4123
> Share Model Weights for Instances on the Same Device

- CMakeLists.txt
Solves libc10.so not found, removes need to LD_LIBRARY_PATH to include pytorch backend dir and resolves segfault during shutdown when loading Onnx models.
> Fix libc10 missing bug on jetson when loading pytorch backend

- src/libtorch.cc
* Disable NvFuser till fixed (Caused by move to 22.03)
* review edits
* Make Nvfuser log a warning instead of info
> Disable NvFuser till fixed (Caused by move to 22.03 PyTorch) (#52)

- README.md
- src/libtorch.cc
- PyTorch does not natively support tensors of string
- We allow users to pass a list of type string instead. For now we allow only 1D lists of strings. This means that batching for string I/O is not supported.
TODO
> Add support for String input/output

- src/libtorch.cc
- Add fall back to enforcing ordering of inputs/outputs for cases when neither naming convention for I/O is met i.e. not an input argument in the model forward function and not using the <name>__<index> format for names.
- These models that failed to follow the naming conventions would earlier fail to load. Now they load successfully and the input/outputs assume the order they are specified in inside the model configuration file.
> Enforce ordering of I/O if naming convention is not followed

- CMakeLists.txt
- src/libtorch.cc
Added these markers for perf profiling for a bug. I think it is good idea to merge it in main for future to avoid repeated work.
See here for header: https://github.com/triton-inference-server/common/blob/main/include/triton/common/nvtx.h
Note: The GPU forward execution is an asynchronous operation in pytorch backend.
> Add nvtx markers which can be useful in perf profiling

- README.md
- src/libtorch.cc
Implemented a flag similar to `memory_arena_shrinkage` in ONNXRuntime backend. With `ENABLE_CACHE_CLEANING` set to `true`, CUDA cache gets cleared after each model execution. This will enable us to serve more models in one GPU. 
I have tested on local GPU: with `enable_cache_cleaning=false`, the model takes additional 2Gi GRAM after running inference with batch size 30. After that, this 2Gi never gets shrunk. With `enable_cache_cleaning=true`, the additional GRAM gets shrunk every time after model execution.
> Add CUDA cache cleaning flag to pytorch backend

- src/libtorch.cc
By this point, the responses are sent but we keep the pointer reference to identify if the request are processed successfully for `TRITONBACKEND_ModelInstanceReportStatistics`. As a result, `RESPOND_ALL_AND_SET_TRUE_IF_ERROR` may send a response twice and cause memory corruption.
> Fix possible "double send" of responses.

- src/libtorch.cc
The only thing I notice is this deprecation warning, which I figure we can fix in the future if there's a problem with the old API we're using:
> [W cuda_graph_fuser.h:17] Warning: RegisterCudaFuseGraph::registerPass() is deprecated. Please use torch::jit::fuser::cuda::setEnabled(). (function registerPass)
Fixes https://github.com/triton-inference-server/server/issues/5128
> re-enable nvfuser

- CMakeLists.txt
Compile linear algebra library into Pytorch backend to be usable with Triton.
Addresses: https://github.com/triton-inference-server/server/issues/4934
> Package linear algebra library

- src/libtorch.cc
Prevent the PyTorch backend from launching with unsupported data type (e.g. uint64) in sequence_batching in config.pbtxt.
Related PR: https://github.com/triton-inference-server/server/pull/5330
Closes https://github.com/triton-inference-server/server/issues/5276
> Add check for sequence data type

- README.md
nvcr.io/nvidia/pytorch:21.02-py3 doesn't contain /usr/local/lib/python3.8/dist-packages/torch/lib/*, following the build instructions in README.md will fail with errors.
> Update pytorch docker image tag to 22.12 in README.md

- src/libtorch.cc
server PR: https://github.com/triton-inference-server/server/pull/5522
> Add ragged batching support

- src/libtorch.cc
Fixing warning: 
[W cuda_graph_fuser.h:17] Warning: RegisterCudaFuseGraph::registerPass() is deprecated. Please use torch::jit::fuser::cuda::setEnabled(). (function registerPass)
> Fix deprecation warning

- README.md
Based on https://github.com/triton-inference-server/python_backend/pull/233#discussion_r1170484477 discussion, just removing Pytorch 2.0 notes for now until we see more usage.
> Remove Pytorch 2.0 note

- src/libtorch.cc
- src/libtorch_utils.cc
The backend was missing support for `batch_input` inputs, specifically, no batch_input is passed to the model.
I added the ability to pass these inputs through to the model, the same way normal input's are passed through.
I followed the implementation in the onnxruntime_backend, and kept to passing the batch_input data as Tensor on the CPU.
> Add support for batch_input

- src/libtorch.cc
For `MODEL` instance group type,
- Don't specify the device when loading the model so that the backend will not select the device for the model
- For the compute input duration, since only one stream will be used for input collection, we can record the cuda events to calculate the elapsed time. However, for the compute infer duration, since multiple streams will be involved, it is hard to use cuda events as timestamps. Therefore, using `cudaLaunchHostFunc` to launch a callback function to record the timestamp.
Added testing: https://github.com/triton-inference-server/server/pull/5810
Closes: https://github.com/triton-inference-server/server/issues/5694
> Add support for instance group of type 'MODEL'

- README.md
The documentation for https://github.com/triton-inference-server/pytorch_backend/pull/107.
> Add documentation for instance group kind of type 'KIND_MODEL'

- src/libtorch.cc
Addresses https://github.com/triton-inference-server/server/issues/5609
I tried to copy the onnxruntime backend as much as possible. To work with how PyTorch treats input and output names, I've tried to only allow the "INPUT__X/OUTPUT__X" naming convention when a state field is defined.
> Implicit state management

- src/libtorch.cc
PR to fix the crashing when some of the PyTorch inputs have zero size. One example here:
https://github.com/triton-inference-server/server/issues/5972
The error seems tbe be because of `Torch::from_blob` function for copying inputs not working when the tensor is zero-size. The fix is to add the special handle in this case, directly creating a zero-size tensor, instead of calling the PyTorch function.
Tested and it seems to have fixed the crashing.
> fix the crashing when there are zero-size inputs

- src/libtorch.cc
- src/libtorch_utils.cc
- src/libtorch_utils.h
As noted in the issue here: https://github.com/triton-inference-server/server/issues/6896 we have found out the number of threads can affect the pytorch inference performance a lot. In some cases we have seen PyTorch inference runs (super) slow on multi-core CPU machines, and just setting number of instance is not enough to handle the problem. We have tested using `at::set_num_threads(1)` and confirmed this fixes the slow inference issue.
This PR allows to configure `intra_op_thread_count` and `inter_op_thread_count` for pytorch models, similar to other backends such as TF and ONNX, with syntax such as
```
parameters { key: "INTRA_OP_THREAD_COUNT" value: { string_value: "1" } }
parameters { key: "INTER_OP_THREAD_COUNT" value: { string_value: "1" } }
```
> add thread control for pytorch backend

- README.md
- src/libtorch.cc
Adding documentation for the parameters added by this PR #125
> Document the thread count options

- tools/gen_pb_exec_env.sh
Update the Conda installation command to match the one suggested by PyTorch: https://pytorch.org/get-started/locally/
> Update the Conda installation command to match the latest from PyTorch

- CMakeLists.txt
Fixes loading of TorchScript models on 24.05 containers
> Add NVPL libraries to pytorch installation

- README.md
- src/libtorch.cc
We've occasionally had issues when multiple models that use cuDNN, (we sometimes see `CUDNN_INTERNAL_ERROR` and sometimes GPU memory will spike when running a kernel from cuDNN) so have found it beneficial to disable it in our own fork of the repo. It would be helpful to have an option to do this upstreamed.
If it would be helpful I could try and find a repro of the `CUDNN_INTERNAL_ERROR` issue but that may take a bit more time.
> Disable cudnn option

- CMakeLists.txt
- README.md
Adding cusparseLt in the backend installation. Initiated talks to include cusparseLt in the base container if possible.
> Add cusparseLt in the installation to support 24.06

- CMakeLists.txt
fixing path within container. 
iGPU: 
```
root@ffb587b7c078:/workspace# ll /usr/local/cuda/lib64
lrwxrwxrwx 1 root root 25 Aug 16  2023 /usr/local/cuda/lib64 -> targets/aarch64-linux/lib/
``` 
x86: 
```
root@73a140ed6477:/workspace# ll /usr/local/cuda/lib64
lrwxrwxrwx 1 root root 24 Apr 16 02:41 /usr/local/cuda/lib64 -> targets/x86_64-linux/lib/
```
SBSA: 
```
root@8d1d63c5b088:/workspace# ll /usr/local/cuda/lib64
lrwxrwxrwx 1 root root 22 Apr 16 02:42 /usr/local/cuda/lib64 -> targets/sbsa-linux/lib/
```
> Fix location of the dependency library.

- src/libtorch.cc
Move each individual check of string input in model backend repos to the bakend repo. 
Check the [conventional commit type](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
box here and add the label to the github PR.
backend: https://github.com/triton-inference-server/backend/pull/101
tensorflow_backend: https://github.com/triton-inference-server/tensorflow_backend/pull/104
pytorch_backend: https://github.com/triton-inference-server/pytorch_backend/pull/136
onnxruntime_backend: https://github.com/triton-inference-server/onnxruntime_backend/pull/263
python_backend: https://github.com/triton-inference-server/python_backend/pull/370
- CI Pipeline ID:
17021222 and 17057045
Initially just to add missing string input tensor checks to python_backend. Refactored because …
> refactor: Add string input checks

- CMakeLists.txt
**Goal**: Incorporate SBSA builds/tests and extended the smoke tests for x86 and SBSA to include L0_sequence_batcher.
Server changes: https://github.com/triton-inference-server/server/pull/7595
TensorRT Backend changes: https://github.com/triton-inference-server/tensorrt_backend/pull/99
TensorFlow Backend changes: https://github.com/triton-inference-server/tensorflow_backend/pull/106
> RHEL Pytorch Backend SBSA

- src/model.py
- tools/gen_pb_exec_env.sh
Fix L0_pytorch_python_runtime--PyTorch test.
> test: Upgrade Miniconda version for ubuntu 24.04

- CMakeLists.txt
- tools/gen_pb_exec_env.sh
This PR is subset of changes which need to be carried over to the `main` branch after the release
> Update `main` branch post 24.11

- CMakeLists.txt
- README.md
- **Update the symlink (#144)**
- **Downgrade patchelf version from 0.18.0 to 0.17.2 due to patchelf regression (#145)**
> Update default branch post 25.01
